import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
	title: "コンピューターリテラシー 2025",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" className="dark">
			<body>
				<SidebarProvider>
					<div className="flex min-h-screen flex-1">
						<AppSidebar />
						<div className="flex flex-1 flex-col">
							<Header />
							<main className="flex-1 p-2">{children}</main>
						</div>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}

function Header() {
	return (
		<header className="flex h-16 items-center space-x-2 p-4">
			<SidebarTrigger />
			<Link href="/" className="font-bold text-2xl">
				コンピューターリテラシー 2025
			</Link>
		</header>
	);
}
