import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
	title: "bolt tutorial",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" className="dark">
			<body>
				<SidebarProvider>
					<div className="flex min-h-screen">
						<AppSidebar />
						<main className="flex-1 p-4">
							<header className="flex items-center space-x-2">
								<SidebarTrigger />
								<span className="text-2xl font-bold">
									Computer Literacy 2025
								</span>
							</header>
							<div className="p-2">{children}</div>
						</main>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
