import { AppFooter } from "@/components/app-footer";
import { AppHeader } from "@/components/app-header";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "コンピューターリテラシー 2025",
	description: "Generated by create next app",
};

const menuItems = [
	{
		label: "やること",
		url: "/introduction",
		// 最終課題の要件
		// 最終課題のサンプルを提示
		// 使用するツールの説明 (Bolt.new)
	},
	{
		label: "webサイトを作る",
		url: "/getting-started",
		// https://bolt.new/ にアクセス
		// アカウント作成
		// サンプルのプロンプトをコピペで実行
		// 自由にカスタマイズしてみる
	},
	{
		label: "webサイトを公開する",
		url: "/publish",
		// https://bolt.new/ にアクセス
		// アカウント作成
		// サンプルのプロンプトをコピペで実行
		// 自由にカスタマイズしてみる
	},
	{
		label: "HTMLを編集する",
		url: "/html",
		// htmlの構造を説明
		// aタグ
		// imgタグ
		// inputタグ
		// mdn web docsを紹介する https://developer.mozilla.org/ja/docs/Web/HTML/Reference
	},
	{
		label: "CSSを編集する",
		url: "/css",
		// cssの構造を説明
		// background-colorを変えてみる
		// mdn web docsを紹介する https://developer.mozilla.org/ja/docs/Web/CSS/Reference
	},
	{
		label: "JavaScriptを編集する",
		url: "/javascript",
		// JavaScriptの構造を説明
		// mdn web docsを紹介する https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference
	},
	{
		label: "もっと学びたい人へ",
		url: "/advanced",
	},
];

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" className="dark bg-neutral-900">
			<body>
				<SidebarProvider>
					<div className="flex min-h-screen flex-1">
						<AppSidebar menuItems={menuItems} />
						<div className="flex flex-1 flex-col">
							<AppHeader />
							<main className="mx-auto w-full max-w-4xl flex-1 p-8">
								{children}
							</main>
							<AppFooter menuItems={menuItems} />
						</div>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
